# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master", "feat/windows-action" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
      os: ["ubuntu-latest", windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.10"
    - run: pip install setuptools poetry
    - run: poetry install
    - run: poetry add pyinstaller flet
    - run: poetry run flet pack myflet_extlib/main.py    
    - run: ls dist
    - uses: actions/upload-artifact@v2
      with:
        name: myflet_extlib
        path: dist/main.exe
